.PHONY: test install

test:
	@bash test.sh

install:
	@mkdir -p ~/.local/bin
	@cp asciify.sh ~/stow_dotfiles/local/.local/bin/asciify
	@chmod +x ~/.local/bin/asciify
	@echo "Installed asciify to ~/.local/bin/asciify"
